---
- name: Load OS specific variables
  include_vars: "{{ item }}"
  tags:
    - always
    - install
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: install-Debian.yml
  when: ansible_os_family | lower in ['debian', 'ubuntu']
